DEBUG:root:received {"id":1,"src":"c1","dest":"n2","body":{"type":"init","node_id":"n2","node_ids":["n0","n1","n2"],"msg_id":1}}
INFO:root:node n2 initialized
DEBUG:root:sending {"dest": "c1", "src": "n2", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"id":9,"src":"n1","dest":"n2","body":{"msg_id":4,"type":"fwd_msg","vv":{"n0":0,"n1":1,"n2":0},"message":1}}
Traceback (most recent call last):
  File "/home/miguel/uni/4ano/sd/sdge/guiao1/causal-broadcast.py", line 55, in <module>
    if verify_delevery(msg.src, ast.literal_eval(msg.body.vv)):
  File "/usr/lib/python3.10/ast.py", line 110, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.10/ast.py", line 109, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.10/ast.py", line 83, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.10/ast.py", line 74, in _convert_num
    _raise_malformed_node(node)
  File "/usr/lib/python3.10/ast.py", line 71, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string: namespace(n0=0, n1=1, n2=0)
